version: '3.8'
services:
  postgresql:
    image: postgres:alpine
    container_name: "postgresql"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 15s
      retries: 10

  app:
    container_name: "vue-app"
    build:
      context: ./src/vue-app
      dockerfile: Dockerfile.dev
    image: vue-app
    ports:
      - "34002:34002"
    volumes:
      - ./src/vue-app:/app
    command: /bin/sh -c "npm run dev"

networks:
  my-bridge:
    driver: bridge
